### ISSUE TITLE
Multiple items in queue results in crashing pods.

### ISSUE THREAD

**Issue by stvnwrgs** [jenkinsci/kubernetes-plugin#43]
It looks like, that only one slave at a time can be spawned. If i add multiple jobs to the que the following happens:

Sometimes it is creating a slave and executes the first job. Sometimes It is creating two slaves and no jobs starts.

If the first job starts, the second job wont start. Even not after he creates multiple pods. The pods are crashing with Failed to connect to Jenkins. After removing everything from queue and adding one job again, it works.

Attached some logs:

```
Jan 12, 2016 3:17:43 PM WARNING jenkins.util.ErrorLoggingScheduledThreadPoolExecutor afterExecute
failure in task not wrapped in SafeTimerTask
hudson.remoting.RequestAbortedException: hudson.remoting.Channel$OrderlyShutdown
	at hudson.remoting.Request.abort(Request.java:297)
	at hudson.remoting.Channel.terminate(Channel.java:847)
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1080)
	at hudson.remoting.Channel$1.handle(Channel.java:501)
	at hudson.remoting.AbstractByteArrayCommandTransport$1.handle(AbstractByteArrayCommandTransport.java:61)
	at org.jenkinsci.remoting.nio.NioChannelHub$2.run(NioChannelHub.java:594)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to 1239fba207bf(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.Request.call(Request.java:172)
	at hudson.remoting.Channel.call(Channel.java:780)
	at hudson.FilePath.act(FilePath.java:980)
	at hudson.FilePath.act(FilePath.java:969)
	at hudson.FilePath.deleteRecursive(FilePath.java:1171)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController.cleanup(FileMonitoringTask.java:156)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:201)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:150)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: hudson.remoting.Channel$OrderlyShutdown
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1080)
	at hudson.remoting.Channel$1.handle(Channel.java:501)
	at hudson.remoting.AbstractByteArrayCommandTransport$1.handle(AbstractByteArrayCommandTransport.java:61)
	at org.jenkinsci.remoting.nio.NioChannelHub$2.run(NioChannelHub.java:594)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: Command close created at
	at hudson.remoting.Command.<init>(Command.java:56)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1071)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1069)
	at hudson.remoting.Channel.close(Channel.java:1153)
	at hudson.remoting.Channel.close(Channel.java:1135)
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1076)
	at hudson.remoting.Channel$1.handle(Channel.java:498)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:60)

Jan 12, 2016 3:17:43 PM WARNING hudson.remoting.AbstractByteArrayCommandTransport$1 handle
Failed to construct Command
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2335)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2804)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractByteArrayCommandTransport$1.handle(AbstractByteArrayCommandTransport.java:61)
	at org.jenkinsci.remoting.nio.NioChannelHub$2.run(NioChannelHub.java:594)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 12, 2016 3:17:43 PM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
workflow #3 completed: SUCCESS
Jan 12, 2016 3:18:43 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Excess workload after pending Spot instances: 1
Jan 12, 2016 3:18:43 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Kubernetes Pod Template from Kube with 1 executors. Remaining excess workload: 0
Jan 12, 2016 3:18:43 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Created Pod: 124a47146a07
Jan 12, 2016 3:18:43 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (0/100): 124a47146a07
Jan 12, 2016 3:18:44 PM INFO hudson.TcpSlaveAgentListener$ConnectionHandler run
Accepted connection #13 from /172.17.0.1:45716
Jan 12, 2016 3:18:50 PM WARNING hudson.node_monitors.ResponseTimeMonitor$1 monitor
Making eff764ff0aa offline because it’s not responding
Jan 12, 2016 3:18:53 PM INFO hudson.slaves.NodeProvisioner$2 run
Kubernetes Pod Template provisioning successfully completed. We have now 5 computer(s)
Jan 12, 2016 3:20:00 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Terminating Kubernetes instance for slave 124a47146a07
Jan 12, 2016 3:20:00 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Terminated Kubernetes instance for slave 124a47146a07
Jan 12, 2016 3:20:00 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Disconnected computer 124a47146a07
Jan 12, 2016 3:20:00 PM WARNING hudson.remoting.AbstractByteArrayCommandTransport$1 handle
Failed to construct Command
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2335)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2804)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractByteArrayCommandTransport$1.handle(AbstractByteArrayCommandTransport.java:61)
	at org.jenkinsci.remoting.nio.NioChannelHub$2.run(NioChannelHub.java:594)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 12, 2016 3:20:00 PM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
workflow #4 completed: SUCCESS
Jan 12, 2016 3:20:03 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Excess workload after pending Spot instances: 1
Jan 12, 2016 3:20:03 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Kubernetes Pod Template from Kube with 1 executors. Remaining excess workload: 0
Jan 12, 2016 3:20:03 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Created Pod: 125ce773d066
Jan 12, 2016 3:20:03 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (0/100): 125ce773d066
Jan 12, 2016 3:20:09 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (1/100): 125ce773d066
Jan 12, 2016 3:20:15 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (2/100): 125ce773d066
Jan 12, 2016 3:20:21 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (3/100): 125ce773d066
Jan 12, 2016 3:20:27 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (4/100): 125ce773d066
Jan 12, 2016 3:20:33 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (5/100): 125ce773d066
```

Watch on pods:
```
124a47146a07   0/1       Pending   0         0s
124a47146a07   0/1       Pending   0         0s
124a47146a07   0/1       Pending   0         0s
124a47146a07   0/1       Running   0         0s
124a47146a07   1/1       Running   0         2s
124a47146a07   1/1       Terminating   0         1m
124a47146a07   0/1       Terminating   0         1m
125ce773d066   0/1       Pending   0         0s
125ce773d066   0/1       Pending   0         0s
125ce773d066   0/1       Pending   0         0s
124a47146a07   0/1       Terminating   0         1m
124a47146a07   0/1       Terminating   0         1m
124a47146a07   0/1       Terminating   0         1m
125ce773d066   0/1       Running   0         1m
125ce773d066   1/1       Running   0         1m
125ce773d066   0/1       Error     0         1m
12822f70f25e   0/1       Pending    0        0s
12822f70f25e   0/1       Pending   0         0s
12822f70f25e   0/1       Pending   0         0s
12822f70f25e   0/1       Running   0         0s
12822f70f25e   1/1       Running   0         2s
12822f70f25e   0/1       Error     0         33s
```

The Pods that have an error is saying the following:

```
Jan 12, 2016 3:22:43 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: 12822f70f25e
Jan 12, 2016 3:22:43 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Jan 12, 2016 3:22:43 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://jenkins.default.cluster.local:8080]
Jan 12, 2016 3:23:08 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to http://jenkins.default.cluster.local:8080/tcpSlaveAgentListener/: jenkins.default.cluster.local
java.io.IOException: Failed to connect to http://jenkins.default.cluster.local:8080/tcpSlaveAgentListener/: jenkins.default.cluster.local
	at hudson.remoting.Engine.run(Engine.java:208)
Caused by: java.net.UnknownHostException: jenkins.default.cluster.local
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
	at hudson.remoting.Engine.run(Engine.java:205)
```

My Settings are:

number of executers: 0

Connection Timeout: 5
Read Timeout; 15
Container Cap: 20
Container Cleanup Timeout: 5

1 Image

Max number of instances: 5

This Ticket is maybe relating to #20 ?

Is there something missconfigured? Im wondering why it says: 
`Started provisioning Kubernetes Pod Template from Kube with 1 executors. Remaining excess workload: 0`

**Comment by carlossg** [comment]
seems to me that the slave can't connect to jenkins in `jenkins.default.cluster.local`, are you running the jenkins master in k8s and the service is properly configured?

**Comment by carlossg** [comment]
please open issue under https://issues.jenkins-ci.org/browse/JENKINS if still needed
