### ISSUE TITLE
Slave went offline during the build (java.io.EOFException)

### ISSUE THREAD

**Issue by listx** [jenkinsci/kubernetes-plugin#49]
tail -f /var/jenkins_home/logs/slaves/4ceb45ef3bb3/slave.log:

```
JNLP agent connected from /10.2.41.1
<===[JENKINS REMOTING CAPACITY]===>Slave.jar version: 2.53.2
This is a Unix slave
Slave successfully connected and online
ERROR: Connection terminated
ha:AAAAWB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0ldFVf2c+b/lb5MDAwVRQxSaBqcITRIIQMEMIIUFgAAckCEiWAAAAA=java.io.EOFException
	at org.jenkinsci.remoting.nio.NioChannelHub$3.run(NioChannelHub.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Build's console output:

```
Started by user Linus Arver
Building remotely on 4ceb45ef3bb3 (slave) in workspace /home/jenkins-slave/workspace/test
Cloning the remote Git repository
Cloning repository https://xxxxxxxxxxxxxxxxxxxx@github.com/xxxxxx/xxxx
 > git init /home/jenkins-slave/workspace/test # timeout=10
Fetching upstream changes from https://xxxxxxxxxxxxxxxxxxxx@github.com/xxxxxx/xxxx
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://xxxxxxxxxxxxxxxxxxxx@github.com/xxxxxx/xxxx +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://xxxxxxxxxxxxxxxxxxxx@github.com/xxxxxx/xxxx # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://xxxxxxxxxxxxxxxxxxxx@github.com/xxxxxx/xxxx # timeout=10
Fetching upstream changes from https://xxxxxxxxxxxxxxxxxxxx@github.com/xxxxxx/xxxx
 > git -c core.askpass=true fetch --tags --progress https://xxxxxxxxxxxxxxxxxxxx@github.com/xxxxxx/xxxx +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/test-dep^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/test-dep^{commit} # timeout=10
Checking out Revision a3033ab98472f035d5ce32dd60d26a5196da6d8d (refs/remotes/origin/test-dep)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a3033ab98472f035d5ce32dd60d26a5196da6d8d
 > git rev-list a3033ab98472f035d5ce32dd60d26a5196da6d8d # timeout=10
[test] $ /bin/sh -xe /tmp/hudson3246410542428863996.sh
+ sleep 20m
Slave went offline during the build
Build step 'Execute shell' marked build as failure
FATAL: channel is already closed
hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.remoting.Channel.send(Channel.java:578)
	at hudson.remoting.Request.call(Request.java:130)
	at hudson.remoting.Channel.call(Channel.java:780)
	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:953)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:540)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.io.EOFException
	at org.jenkinsci.remoting.nio.NioChannelHub$3.run(NioChannelHub.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE
```

Has anyone been able to actually use this plugin successfully without the slaves disconnecting? For the slave contaienrs I've tried all sorts of combination of various Remoting versions, jre versions, etc to no avail.
They always disconnect with this same "Slave went offline during the build" message (the command I run in the build is simply `sleep 20m`).
The Jenkins master is on 1.642.1.

This might be related to https://issues.jenkins-ci.org/browse/JENKINS-31050 but I am not sure.

**Comment by mikesplain** [comment]
It works fine for me. Just did the same test, sleep for 20m and no disconnect. 


Jenkins v1.646
K8s v1.1.3




Mike Splain
Lead DevOps Engineer
610.304.6098
mike.splain@barkly.com
www.barkly.com

**Comment by carlossg** [comment]
works fine here, I've seen EOFExceptions but with no consequences
