### ISSUE TITLE
Got java.io.EOFException when slave is disconnected

### ISSUE THREAD

**Issue by mfojtik** [jenkinsci/kubernetes-plugin#52]
Note that this is not a functionality bug, everything works perfectly fine, the slave disappears, etc.
It is just annoying error in the Jenkins server log ;-) 

```console
INFO: Terminated Kubernetes instance for slave 2a249e03609
160	Feb 10, 2016 12:50:43 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
161	INFO: Disconnected computer 2a249e03609
162	Feb 10, 2016 12:50:43 PM hudson.remoting.AbstractByteArrayCommandTransport$1 handle
163	WARNING: Failed to construct Command
164	java.io.EOFException
165		at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2335)
166		at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2804)
```

**Comment by carlossg** [comment]
Seen this and it's a problem on the Jenkins core side
