### ISSUE TITLE
NullPointerException - Kube Plugin  0.2 with Docker plugin 0.9.4 

### ISSUE THREAD

**Issue by jeffbean** [jenkinsci/kubernetes-plugin#6]
Reproduction steps:

`Kubernetes 1.0`

Jenkins server:
`docker run -p 8080:8080 -p 50000:50000 -v /var/jenkins:/var/jenkins_home jenkins`
Jenkins ver. 1.609.2

Installed Kubernetes Plugin 0.2 from plugin manager. 
```
SEVERE: Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@624e1af1 failed
java.lang.NoSuchMethodError: com.nirima.jenkins.plugins.docker.DockerTemplate.getDisplayName()Ljava/lang/String;
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.provision(KubernetesCloud.java:234)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:678)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:284)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:57)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:773)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Uninistalled Docker plugin 0.11.0 and manually installed 0.9.4:
```
Aug 07, 2015 4:45:23 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Excess workload after pending Spot instances: 1
Aug 07, 2015 4:45:23 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
WARNING: Failed to count the # of live instances on Kubernetes
java.lang.NullPointerException
	at com.nirima.jenkins.plugins.docker.DockerTemplateBase.getImage(DockerTemplateBase.java:156)
	at com.nirima.jenkins.plugins.docker.DockerTemplateBase.getDisplayName(DockerTemplateBase.java:207)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.provision(KubernetesCloud.java:234)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:678)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:284)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:57)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:773)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by carlossg** [comment]
Docker plugins is no longer used in master, so this won't apply anymore
