### ISSUE TITLE
Any support for Kubernetes 1.0.x?

### ISSUE THREAD

**Issue by joshm1** [jenkinsci/kubernetes-plugin#7]
Is there any work in progress for this to support Kubernetes 1.0.x, or does it already exist?  I'm trying to get this installed on my Kuberentes 1.0.1 cluster and didn't realize until I ran into the following issues that it seems like this is using a Kuberentes API client for v1beta2 (per https://github.com/nirmal070125/KubernetesAPIJavaClient/blob/master/src/main/java/com/github/kubernetes/java/client/interfaces/KubernetesAPIClientInterface.java#L36). The Dockerfile is referencing version `0.1-20150214.103149-1` and hasn't been updated in 6 months.

For reference, the error in Jenkins is:

```
Caused by: javax.ws.rs.ProcessingException: Unable to find a MessageBodyReader of content-type text/html;charset=utf-8 and type class com.github.kubernetes.java.client.exceptions.Status
	at org.jboss.resteasy.core.interception.ClientReaderInterceptorContext.throwReaderNotFound(ClientReaderInterceptorContext.java:39)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.getReader(AbstractReaderInterceptorContext.java:73)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:248)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:181)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:217)
	at com.github.kubernetes.java.client.exceptions.KubernetesClientException.getResponse(KubernetesClientException.java:47)
	at com.github.kubernetes.java.client.exceptions.KubernetesClientException.buildMessage(KubernetesClientException.java:53)
	at com.github.kubernetes.java.client.exceptions.KubernetesClientException.<init>(KubernetesClientException.java:37)
	at com.github.kubernetes.java.client.v2.KubernetesApiClient.getAllPods(KubernetesApiClient.java:66)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$DescriptorImpl.doTestConnection(KubernetesCloud.java:389)
```

**Comment by ngbinh** [comment]
:+1:

**Comment by elibixby** [comment]
Really should move to the autogenerated swagger api client, so it can stay up to date, (once the kubernetes swagger spec moves to 2.0, so the libraries are a little better)

**Comment by carlossg** [comment]
The support for 1.0 is in master, not yet released, something I plan to do before my Jenkins User Conference talk next week.

**Comment by ndeloof** [comment]
@elibixby is this autogenerated  swagger api client available somewhere ? (can't find it)
I'd like to move out from fabric8, which has incompatible dependencies and make the plugin a huge file to distribute.

**Comment by elibixby** [comment]
@ndeloof I don't think the result is hosted anywhere, we could set up a CI to host it somewhere (I could ask around to see if I can get it hosted in the github.com/kubernetes org). I was using https://github.com/swagger-api/swagger-codegen/ to generate it. There are some bugs (Any types are not recognized as Map<String, String> being the main one). I think the autogenerated code is supposed to be a lot better for swagger 2.0 specs, and moving the kubernetes swagger spec to 2.0 is on the roadmap for the near future.
